### ISSUE TITLE
Plugin Errors out in case of missing date-name attr

### ISSUE THREAD

**Issue by saleem-latif** [MrFirthy/jquery-progresstracker#3]
Hi,

Plugin errors out in case of missing data-name attr.

Error Message:
Uncaught TypeError: Cannot read property 'length' of undefined

I have fixed the bug and can upload it here given that you grant me access rights for uploading branches and creating pull-requests.

great plugin by the way :+1: 
Thanks

**Comment by MrFirthy** [comment]
Hi @saleem-latif 

Thanks that sounds great. I've just granted you access so feel free to submit a pull request. 

Apologies for the very late reply too!
